import type { ScheduleData } from "./schedule-types";

export const DEMO_SCHEDULE: ScheduleData = {
  id: "demo-restaurant",
  createdAt: new Date().toISOString(),
  employees: [
    {
      id: "emp-1",
      name: "Marco",
      role: "cook",
      contractType: "fulltime",
      contractHours: 38,
      isMinor: false,
      preferences: "",
    },
    {
      id: "emp-2",
      name: "Sophie",
      role: "cook",
      contractType: "parttime",
      contractHours: 24,
      isMinor: false,
      preferences: "No Sundays",
    },
    {
      id: "emp-3",
      name: "Jan",
      role: "server",
      contractType: "fulltime",
      contractHours: 38,
      isMinor: false,
      preferences: "",
    },
    {
      id: "emp-4",
      name: "Lisa",
      role: "server",
      contractType: "parttime",
      contractHours: 20,
      isMinor: false,
      preferences: "Prefers evenings",
    },
    {
      id: "emp-5",
      name: "Thomas",
      role: "server",
      contractType: "student",
      contractHours: 12,
      isMinor: false,
      preferences: "Only available Thu-Sun",
    },
    {
      id: "emp-6",
      name: "Emma",
      role: "server",
      contractType: "oncall",
      contractHours: 0,
      isMinor: false,
      preferences: "",
    },
    {
      id: "emp-7",
      name: "Daan",
      role: "bartender",
      contractType: "parttime",
      contractHours: 24,
      isMinor: false,
      preferences: "",
    },
    {
      id: "emp-8",
      name: "Fleur",
      role: "host",
      contractType: "parttime",
      contractHours: 16,
      isMinor: false,
      preferences: "No late evenings",
    },
    {
      id: "emp-9",
      name: "Sem",
      role: "dishwasher",
      contractType: "student",
      contractHours: 12,
      isMinor: true,
      preferences: "School until 15:00 on weekdays",
    },
    {
      id: "emp-10",
      name: "Nina",
      role: "server",
      contractType: "oncall",
      contractHours: 0,
      isMinor: false,
      preferences: "Weekends only",
    },
  ],
  requirements: [
    {
      dayPart: "morning",
      roles: { cook: 1, server: 2, dishwasher: 1 },
    },
    {
      dayPart: "afternoon",
      roles: { cook: 1, server: 2, bartender: 1, host: 1 },
    },
    {
      dayPart: "evening",
      roles: { cook: 2, server: 4, bartender: 1, dishwasher: 1, host: 1 },
    },
  ],
  availability: [
    {
      employeeId: "emp-1",
      slots: {
        monday: ["morning", "afternoon", "evening"],
        tuesday: ["morning", "afternoon", "evening"],
        wednesday: ["morning", "afternoon", "evening"],
        thursday: ["morning", "afternoon", "evening"],
        friday: ["morning", "afternoon", "evening"],
        saturday: ["afternoon", "evening"],
        sunday: ["afternoon", "evening"],
      },
    },
    {
      employeeId: "emp-2",
      slots: {
        monday: ["morning", "afternoon"],
        tuesday: ["morning", "afternoon", "evening"],
        wednesday: ["morning", "afternoon"],
        thursday: ["morning", "afternoon", "evening"],
        friday: ["morning", "afternoon", "evening"],
        saturday: ["morning", "afternoon"],
      },
    },
    {
      employeeId: "emp-3",
      slots: {
        monday: ["morning", "afternoon", "evening"],
        tuesday: ["morning", "afternoon", "evening"],
        wednesday: ["morning", "afternoon", "evening"],
        thursday: ["morning", "afternoon", "evening"],
        friday: ["morning", "afternoon", "evening"],
        saturday: ["morning", "afternoon", "evening"],
        sunday: ["morning", "afternoon", "evening"],
      },
    },
    {
      employeeId: "emp-4",
      slots: {
        monday: ["afternoon", "evening"],
        tuesday: ["afternoon", "evening"],
        wednesday: ["evening"],
        thursday: ["afternoon", "evening"],
        friday: ["afternoon", "evening"],
        saturday: ["afternoon", "evening"],
        sunday: ["afternoon", "evening"],
      },
    },
    {
      employeeId: "emp-5",
      slots: {
        thursday: ["evening"],
        friday: ["evening"],
        saturday: ["afternoon", "evening"],
        sunday: ["afternoon", "evening"],
      },
    },
    {
      employeeId: "emp-6",
      slots: {
        monday: ["morning", "afternoon", "evening"],
        tuesday: ["morning", "afternoon", "evening"],
        wednesday: ["morning", "afternoon", "evening"],
        thursday: ["morning", "afternoon", "evening"],
        friday: ["morning", "afternoon", "evening"],
        saturday: ["morning", "afternoon", "evening"],
        sunday: ["morning", "afternoon", "evening"],
      },
    },
    {
      employeeId: "emp-7",
      slots: {
        tuesday: ["afternoon", "evening"],
        wednesday: ["afternoon", "evening"],
        thursday: ["afternoon", "evening"],
        friday: ["afternoon", "evening"],
        saturday: ["afternoon", "evening"],
        sunday: ["afternoon", "evening"],
      },
    },
    {
      employeeId: "emp-8",
      slots: {
        monday: ["morning", "afternoon"],
        wednesday: ["morning", "afternoon"],
        friday: ["morning", "afternoon"],
        saturday: ["morning", "afternoon"],
        sunday: ["morning", "afternoon"],
      },
    },
    {
      employeeId: "emp-9",
      slots: {
        monday: ["evening"],
        tuesday: ["evening"],
        wednesday: ["evening"],
        thursday: ["evening"],
        friday: ["evening"],
        saturday: ["morning", "afternoon", "evening"],
        sunday: ["morning", "afternoon", "evening"],
      },
    },
    {
      employeeId: "emp-10",
      slots: {
        friday: ["evening"],
        saturday: ["morning", "afternoon", "evening"],
        sunday: ["morning", "afternoon", "evening"],
      },
    },
  ],
  schedule: null,
};
